Finished ShiftLogger Application.
TheCSharpAcademy/CodeReviews.Console.ShiftsLogger pull request #51
Opened 2024-07-25 17:52 UTC by N-Endy

I welcome insight on different ways to make the project better

2024-07-29 14:15 UTC, Doc415 requested changes
Very good work. It is working flawless. I was about to approve but there is one missing part  :<
The project lacks a requirement. 

** Your front-end project needs to have try-catch blocks around the API calls so it handles unexpected errors (i.e. the API isn't running or returns a 500 error.)

You should also remove unused files and code blocks
![image](https://github.com/user-attachments/assets/ef85e9c5-0e65-458d-bad0-07f30cd29eef)

2024-07-30 11:04 UTC, N-Endy commented
Thank you doc.
I'll make sure to make the necessary changes.

On Mon, Jul 29, 2024 at 3:16 PM SERDAR SİPAHİOĞLU ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Very good work. It is working flawless. I was about to approve but there
> is one missing part :<
> The project lacks a requirement.
>
> ** Your front-end project needs to have try-catch blocks around the API
> calls so it handles unexpected errors (i.e. the API isn't running or
> returns a 500 error.)
>
> You should also remove unused files and code blocks
> image.png (view on web)
> <https://github.com/user-attachments/assets/ef85e9c5-0e65-458d-bad0-07f30cd29eef>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheCSharpAcademy/CodeReviews.Console.ShiftsLogger/pull/51#pullrequestreview-2205107980>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM3CH7QYVTT2NP5CFRIDP53ZOZFDFAVCNFSM6AAAAABLPA6AG2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMBVGEYDOOJYGA>
> .
> You are receiving this because you authored the thread.Message ID:
> <TheCSharpAcademy/CodeReviews.Console.
> ***@***.***>
>

2024-07-30 11:39 UTC, N-Endy commented
Try-catch blocks have been added to the API calls, and the code for
WeatherForecast has been deleted.
Thank you.

On Mon, Jul 29, 2024 at 3:16 PM SERDAR SİPAHİOĞLU ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Very good work. It is working flawless. I was about to approve but there
> is one missing part :<
> The project lacks a requirement.
>
> ** Your front-end project needs to have try-catch blocks around the API
> calls so it handles unexpected errors (i.e. the API isn't running or
> returns a 500 error.)
>
> You should also remove unused files and code blocks
> image.png (view on web)
> <https://github.com/user-attachments/assets/ef85e9c5-0e65-458d-bad0-07f30cd29eef>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheCSharpAcademy/CodeReviews.Console.ShiftsLogger/pull/51#pullrequestreview-2205107980>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM3CH7QYVTT2NP5CFRIDP53ZOZFDFAVCNFSM6AAAAABLPA6AG2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMBVGEYDOOJYGA>
> .
> You are receiving this because you authored the thread.Message ID:
> <TheCSharpAcademy/CodeReviews.Console.
> ***@***.***>
>

2024-07-30 20:51 UTC, Doc415 approved these changes

2024-07-30 20:52 UTC, closed without merging